### ISSUE TITLE
Add shortcut configuration to add custom model resolvers

### ISSUE THREAD

**Issue by iltar** [iltar/http-bundle#19]
In #17 it was made easier to implement custom model resolvers. However, there's no configuration option to add this. Ideally I'd see something like a tag to collect the descriptors and create a reference. A priority could be added. The other option would be to create config options:

``` yml
iltar_http:
    router:
        model_descriptors:
            app.descriptor.propel: 150
            app.descriptor.eloquent: 50
```
